// Parser for the custom (non-tagged-property) serialization of UEdGraphPin arrays
// that UEdGraphNode::Serialize appends after its tagged properties in UNCOOKED
// editor assets. UAssetAPI leaves these bytes in Export.Extras; the pin array
// begins at offset 0 of Extras for EdGraphNode-derived exports.
//
// Format transcribed from UE 5.6 sources:
//   Engine/Source/Runtime/Engine/Private/EdGraph/EdGraphPin.cpp
//     UEdGraphPin::SerializeAsOwningNode / SerializePinArray / SerializePin /
//     UEdGraphPin::Serialize / FEdGraphPinType::Serialize
//   Engine/Source/Runtime/Engine/Private/EdGraph/EdGraphNode.cpp
//     operator<<(FArchive&, FEdGraphTerminalType&)

using System.Text;
using UAssetAPI;
using UAssetAPI.CustomVersions;
using UAssetAPI.PropertyTypes.Objects;
using UAssetAPI.UnrealTypes;

namespace BlueprintJson;

public class PinRef
{
    public bool IsNull = true;
    public FPackageIndex OwningNode;   // export index of the other pin's node
    public Guid PinId;
}

public class PinTypeInfo
{
    public string Category, SubCategory;
    public FPackageIndex SubCategoryObject;
    public byte ContainerType;         // EPinContainerType: 0 None, 1 Array, 2 Set, 3 Map
    // FEdGraphTerminalType (map value type), only when ContainerType == Map
    public string TermCategory, TermSubCategory;
    public FPackageIndex TermSubCategoryObject;
    public bool TermIsConst, TermIsWeak, TermIsUObjectWrapper;
    // FSimpleMemberReference
    public FPackageIndex MemberParent;
    public string MemberName;
    public Guid MemberGuid;
    public bool IsReference, IsWeakPointer, IsConst, IsUObjectWrapper, SinglePrecisionFloat;
}

public class GraphPin
{
    public FPackageIndex OwningNode;
    public Guid PinId;
    public string PinName;
    public string FriendlyName;
    public int SourceIndex;
    public string ToolTip;
    public byte Direction;             // 0 input, 1 output
    public PinTypeInfo Type;
    public string DefaultValue;
    public int DefaultValueStart, DefaultValueEnd;  // byte range of the DefaultValue FString within Extras
    public string AutogeneratedDefaultValue;
    public FPackageIndex DefaultObject;
    public string DefaultTextValue;
    public List<PinRef> LinkedTo = new();
    public List<PinRef> SubPins = new();
    public PinRef ParentPin, PassThrough;
    public Guid PersistentGuid;
    public uint BitField;              // bit 0 bHidden, 1 bNotConnectable, 2 bDefaultValueIsReadOnly, 3 bDefaultValueIsIgnored, 4 bAdvancedView, 5 bOrphanedPin

    public bool Hidden => (BitField & 1) != 0;
    public bool AdvancedView => (BitField & 16) != 0;
    public bool Orphaned => (BitField & 32) != 0;
}

public class NodePins
{
    public List<GraphPin> Pins = new();
    public int TrailingBytes;          // bytes after the pin array (subclass custom serialization, e.g. UK2Node_EditablePinBase user-defined pins)
    public string Error;               // non-null if parsing failed
}

public static class PinBlob
{
    public static NodePins Parse(UAsset asset, byte[] extras)
    {
        var result = new NodePins();
        if (extras == null || extras.Length < 4) { result.Error = "no extras data"; return result; }

        using var ms = new MemoryStream(extras, writable: false);
        using var reader = new AssetBinaryReader(ms, asset);
        try
        {
            int count = reader.ReadInt32();
            if (count < 0 || count > 4096) { result.Error = $"implausible pin count {count}"; return result; }
            for (int i = 0; i < count; i++)
            {
                var pin = new GraphPin();
                ReadPinRef(reader, asset, owning: true, pin);
                result.Pins.Add(pin);
            }
            result.TrailingBytes = (int)(ms.Length - ms.Position);
        }
        catch (Exception ex)
        {
            result.Error = $"{ex.GetType().Name}: {ex.Message} @extras+{ms.Position}";
            result.Pins.Clear();
        }
        return result;
    }

    // Reads one SerializePin entry. When owning, also reads the full pin body into `pin`.
    // For non-owning entries returns the reference triple.
    static PinRef ReadPinRef(AssetBinaryReader reader, UAsset asset, bool owning, GraphPin pin = null)
    {
        var r = new PinRef();
        bool isNull = reader.ReadInt32() != 0;   // bool bNullPtr, serialized as uint32
        if (isNull) return r;
        r.IsNull = false;
        r.OwningNode = new FPackageIndex(reader.ReadInt32());
        r.PinId = reader.ReadGuid();
        if (owning)
        {
            // UEdGraphPin::Serialize re-serializes OwningNode and PinId at the start of the body,
            // duplicating the reference triple SerializePin just wrote.
            pin.OwningNode = new FPackageIndex(reader.ReadInt32());
            pin.PinId = reader.ReadGuid();
            if (pin.PinId != r.PinId) throw new InvalidDataException("pin body PinId does not match reference PinId");
            ReadPinBody(reader, asset, pin);
        }
        return r;
    }

    static void ReadPinBody(AssetBinaryReader reader, UAsset asset, GraphPin pin)
    {
        if (asset.GetCustomVersion<FFrameworkObjectVersion>() < FFrameworkObjectVersion.PinsStoreFName)
            throw new NotSupportedException("asset predates PinsStoreFName; only UE 5.x uncooked assets are supported");

        pin.PinName = reader.ReadFName()?.ToString();
        pin.FriendlyName = ReadFTextAsString(reader, asset);   // present because uncooked assets keep editor-only data

        // FUE5MainStreamObjectVersion::EdGraphPinSourceIndex == 50 (UAssetAPI has no enum for this stream)
        if (asset.GetCustomVersion("FUE5MainStreamObjectVersion") >= 50)
            pin.SourceIndex = reader.ReadInt32();

        pin.ToolTip = reader.ReadFString()?.Value;
        pin.Direction = reader.ReadByte();                     // TEnumAsByte<EEdGraphPinDirection>
        pin.Type = ReadPinType(reader, asset);

        pin.DefaultValueStart = (int)reader.BaseStream.Position;
        pin.DefaultValue = reader.ReadFString()?.Value;
        pin.DefaultValueEnd = (int)reader.BaseStream.Position;

        pin.AutogeneratedDefaultValue = reader.ReadFString()?.Value;
        pin.DefaultObject = new FPackageIndex(reader.ReadInt32());
        pin.DefaultTextValue = ReadFTextAsString(reader, asset);

        pin.LinkedTo = ReadPinRefArray(reader, asset);
        pin.SubPins = ReadPinRefArray(reader, asset);
        pin.ParentPin = ReadPinRef(reader, asset, owning: false);
        pin.PassThrough = ReadPinRef(reader, asset, owning: false);

        pin.PersistentGuid = reader.ReadGuid();                // editor-only tail, present in uncooked assets
        pin.BitField = reader.ReadUInt32();
    }

    static List<PinRef> ReadPinRefArray(AssetBinaryReader reader, UAsset asset)
    {
        int n = reader.ReadInt32();
        if (n < 0 || n > 4096) throw new InvalidDataException($"implausible pin ref array count {n}");
        var list = new List<PinRef>(n);
        for (int i = 0; i < n; i++) list.Add(ReadPinRef(reader, asset, owning: false));
        return list;
    }

    static PinTypeInfo ReadPinType(AssetBinaryReader reader, UAsset asset)
    {
        var t = new PinTypeInfo();
        t.Category = reader.ReadFName()?.ToString();
        t.SubCategory = reader.ReadFName()?.ToString();
        t.SubCategoryObject = new FPackageIndex(reader.ReadInt32());   // weak object ptr saved as normal object ref
        t.ContainerType = reader.ReadByte();                           // EPinContainerType : uint8
        if (t.ContainerType == 3)                                      // Map -> FEdGraphTerminalType PinValueType
        {
            t.TermCategory = reader.ReadFName()?.ToString();
            t.TermSubCategory = reader.ReadFName()?.ToString();
            t.TermSubCategoryObject = new FPackageIndex(reader.ReadInt32());
            t.TermIsConst = reader.ReadInt32() != 0;
            t.TermIsWeak = reader.ReadInt32() != 0;
            if (asset.GetCustomVersion<FReleaseObjectVersion>() >= FReleaseObjectVersion.PinTypeIncludesUObjectWrapperFlag)
                t.TermIsUObjectWrapper = reader.ReadInt32() != 0;
        }
        t.IsReference = reader.ReadInt32() != 0;
        t.IsWeakPointer = reader.ReadInt32() != 0;
        // VER_UE4_MEMBERREFERENCE_IN_PINTYPE is ancient; always present for UE5 assets
        t.MemberParent = new FPackageIndex(reader.ReadInt32());
        t.MemberName = reader.ReadFName()?.ToString();
        t.MemberGuid = reader.ReadGuid();
        t.IsConst = reader.ReadInt32() != 0;                           // VER_UE4_SERIALIZE_PINTYPE_CONST
        if (asset.GetCustomVersion<FReleaseObjectVersion>() >= FReleaseObjectVersion.PinTypeIncludesUObjectWrapperFlag)
            t.IsUObjectWrapper = reader.ReadInt32() != 0;
        if (asset.GetCustomVersion<FUE5ReleaseStreamObjectVersion>() >= FUE5ReleaseStreamObjectVersion.SerializeFloatPinDefaultValuesAsSinglePrecision)
            t.SinglePrecisionFloat = reader.ReadInt32() != 0;
        return t;
    }

    // Header-less FText body (FText::SerializeText): flags + history. Implemented here rather
    // than through UAssetAPI's TextPropertyData because that lacks a NamedFormat reader, which
    // localized pin friendly names (e.g. "{PinName} location") use.
    static string ReadFTextAsString(AssetBinaryReader reader, UAsset asset)
    {
        reader.ReadUInt32();                                   // ETextFlag
        var history = (TextHistoryType)reader.ReadSByte();
        switch (history)
        {
            case TextHistoryType.None:
                if (asset.GetCustomVersion<FEditorObjectVersion>() >= FEditorObjectVersion.CultureInvariantTextSerializationKeyStability
                    && reader.ReadInt32() != 0)
                    return reader.ReadFString()?.Value;        // culture invariant string
                return null;
            case TextHistoryType.Base:
                reader.ReadFString();                          // namespace
                reader.ReadFString();                          // key
                return reader.ReadFString()?.Value;            // source string
            case TextHistoryType.NamedFormat:
            {
                string fmt = ReadFTextAsString(reader, asset); // SourceFmt (recursive FText)
                int n = reader.ReadInt32();
                for (int i = 0; i < n; i++)
                {
                    reader.ReadFString();                      // argument name
                    _ = new FFormatArgumentValue(reader);      // argument value (may recurse into FText)
                }
                return fmt;
            }
            case TextHistoryType.OrderedFormat:
            {
                string fmt = ReadFTextAsString(reader, asset);
                int n = reader.ReadInt32();
                for (int i = 0; i < n; i++) _ = new FFormatArgumentValue(reader);
                return fmt;
            }
            case TextHistoryType.ArgumentFormat:
            {
                string fmt = ReadFTextAsString(reader, asset);
                int n = reader.ReadInt32();
                for (int i = 0; i < n; i++) _ = new FFormatArgumentData(reader);
                return fmt;
            }
            case TextHistoryType.StringTableEntry:
                reader.ReadFName();                            // table id
                return reader.ReadFString()?.Value;            // key
            default:
                throw new NotSupportedException($"FText history type {history} not supported");
        }
    }

    /// <summary>Serialize a string the way UE saves an FString (empty=0, pure-ANSI, else UTF-16LE).</summary>
    public static byte[] EncodeFString(string s)
    {
        if (string.IsNullOrEmpty(s)) return BitConverter.GetBytes(0);
        bool pureAnsi = s.All(c => c < 0x80);
        using var ms = new MemoryStream();
        using var w = new BinaryWriter(ms);
        if (pureAnsi)
        {
            w.Write(s.Length + 1);
            w.Write(Encoding.ASCII.GetBytes(s));
            w.Write((byte)0);
        }
        else
        {
            w.Write(-(s.Length + 1));
            w.Write(Encoding.Unicode.GetBytes(s));
            w.Write((ushort)0);
        }
        w.Flush();
        return ms.ToArray();
    }
}
