name: CI Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake tcc
    - name: Configure CMake (Linux GCC)
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build (GCC)
      run: cmake --build build --config Release
    # Check that our C code is reasonably portable
    - name: Build with TCC
      run: |
        tcc -c Source/ThirdParty/netarch/sam2.c \
        -ISource/UnrealLibretro/Private \
        -ISource/ThirdParty/zstd/lib \
        -ISource/ThirdParty/libjuice/include \
        -ISource/ThirdParty/libuv/include

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: brew install cmake
    - name: Configure CMake (macOS Clang)
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --config Release

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
    - name: Configure CMake (Windows MSVC)
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --config Release