name: netarch

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install dependencies for GUI build
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          tcc \
          libgl1-mesa-dev \
          libx11-dev \
          libxext-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libxi-dev \
          libxfixes-dev \
          libasound2-dev
    - name: Configure CMake (Linux GCC)
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
    - name: Build (GCC)
      run: cmake --build build --parallel
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: netarch-linux-amd64
        path: build/netarch

    - name: Run sam2_test.c
      run: |
        tcc -DSAM2_IMPLEMENTATION \
        -DSAM2_TEST_MAIN \
        -ISource/UnrealLibretro/Private \
        -ISource/ThirdParty/libuv/include \
        -run Source/ThirdParty/netarch/sam2_test.c

    - name: Run ulnet_test.c
      run: |
        tcc -DSAM2_IMPLEMENTATION \
        -DULNET_IMPLEMENTATION \
        -DULNET_TEST_MAIN \
        -ISource/UnrealLibretro/Private \
        -ISource/ThirdParty/zstd/lib \
        -ISource/ThirdParty/libjuice/include \
        -ISource/ThirdParty/libjuice/include/juice \
        Source/UnrealLibretro/Private/LibretroThirdPartyImplementation.c \
        Source/UnrealLibretro/Private/fec.c \
        Source/ThirdParty/zstd/lib/decompress/huf_decompress_amd64.S \
        -run Source/ThirdParty/netarch/ulnet_test.c

  build-macos-x86_64:
    runs-on: macos-13 # Intel runner
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Configure CMake (macOS x86_64)
      run: |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_OSX_ARCHITECTURES="x86_64" \
          -DCMAKE_OSX_DEPLOYMENT_TARGET="11.0"
    - name: Build (macOS x86_64)
      run: cmake --build build --parallel
    - name: Upload macOS x86_64 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: netarch-macos-x86_64
        path: build/netarch
        if-no-files-found: error

  build-macos-arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Configure CMake (macOS arm64)
      run: |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_OSX_ARCHITECTURES="arm64" \
          -DCMAKE_OSX_DEPLOYMENT_TARGET="11.0"
    - name: Build (macOS arm64)
      run: cmake --build build --parallel
    - name: Upload macOS arm64 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: netarch-macos-arm64 # Specific name for this arch
        path: build/netarch
        if-no-files-found: error

  build-windows:
    runs-on: windows-2025 # Fixes issue with SDL that exists as of windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Configure CMake (Windows MSVC)
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
    - name: Build
      run: cmake --build build --config Debug --parallel
    - name: List Windows Build Directory Contents
      run: |
        echo "--- Contents of ./build directory (recursive) on Windows ---"
        Get-ChildItem -Path build -Recurse
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: netarch-windows-amd64
        path: build/Debug/netarch.exe
